02-VueCalc
js-tasks-ru/vue-20230710_ruslan-mingalimov pull request #3
Opened 2023-07-18 21:46 UTC by CharismaRM

2023-07-19 07:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-20 21:55 UTC, ShGKme requested changes
Требуется избавиться от лишнего свойства и побочного эффекта в `computed`

2023-07-20 21:55 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +   }
Вычисляемые свойства - это такие свойства, значения которых (автоматически) определяется функцией вычисления. Vue будет сам вызывать эту функцию, чтобы обновить значение одноимённого ей свойства с результатом этой функции.

Эта функция должна выполнять только одну задачу - вычислять и возвращать значение этого свойства.

Вычисляемые свойства при своём вычислении **ни в коем случае не должны иметь побочных эффектов, не должны изменять состояние, не должны изменять другие свойства**.

Мы не вызываем функцию сами, не контролируем её вызов. Мутация состояния в вычисляемом свойстве может привести к ошибкам и проблемам при отладке из-за неожиданного поведения, когда значения поменялись не тогда, когда ожидалось.

Это также нарушает непосредственно концепцию вычисляемого свойства во Vue о том, что вычисляемое свойство - именно свойство с вычисленным значением.

2023-07-20 21:55 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +   }
Это вычисляемое свойство не только вычисляет результат (который далее доступен как значение вычисляемого свойства в свойстве компонента `calculationActions`, но и мутирует состояние компонента в `this.actions.result`.

При этом `this.actions.result` нигде и никак всё равно не используется

2023-08-03 16:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-03 17:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-03 20:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-08-04 19:17 UTC, ShGKme requested changes
В `02-components/01-CounterButtonComponent` требуется добавить событие в `emits`, остальные задачи приняты

2023-08-04 19:17 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Хотя компонент работает и без этого, все порождаемые компонентом события крайне желательно описывать в опции `emits`:

- Это документирует компонент как для разработчиков, так и для инструментов, IDE
- В случае если имя события совпадает с именем нативного события, например, `click`, установленный обработчик сработает дважды - для нативного события и для события компонента.

2023-08-04 19:17 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +         result:0,
Свойство `result` сейчас просто хранит 0, чтобы вернуться в вычисляемом свойстве для незнакомого оператора.

2023-08-05 12:17 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-07 19:02 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-08-07 19:03 UTC, merged